# Nome da aplicação
server.servlet.context-path=/lumicash
spring.application.name=LumiCash

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/lumicash
spring.datasource.username=postgres
spring.datasource.password=ifpb
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.sql.init.mode=always

# Porta do servidor
server.port=8080


logging.level.org.springframework.security=DEBUG
